#!/usr/bin/env ruby
# frozen_string_literal: true

# Rules enforced here rather than trusted to habit: no em-dashes, no tool
# attribution or mention of AI anywhere in the tracked tree, and no first person
# in the documentation, which describes the project rather than its author.
BANNED = {
  "em-dash" => /—/,
  "en-dash in prose" => /–/,
  "tool attribution" => /\b(claude|copilot|chatgpt|codex|cursor\.sh)\b/i,
  "generated-by claim" => /generated by ai|ai-assisted|written by ai|co-authored-by: *(claude|copilot)/i,
  "mention of AI" => /\b(AI|LLM|LLMs|GPT)\b/
}.freeze

# Prose only: code legitimately has a loop variable named i, never I.
FIRST_PERSON = /(?<![\w'])(I|I'm|I've|I'd|my|me|mine|myself)(?![\w'])/

SKIP = %r{\A(LICENSE|uv\.lock|corpus/|evidence/|script/check_prose\.rb)}

failures = `git ls-files`.each_line(chomp: true).flat_map do |file|
  next [] if file.match?(SKIP)
  next [] unless File.file?(file)
  next [] if File.binread(file, 8000).to_s.include?("\x00")

  # Read as UTF-8 and scrub, so the check does not depend on the locale the
  # shell happens to be running under.
  File.read(file, encoding: "UTF-8").scrub.each_line.with_index.flat_map do |line, index|
    found = BANNED.filter_map do |label, pattern|
      "#{file}:#{index + 1}: #{label}: #{line.strip}" if line.match?(pattern)
    end
    if file.end_with?(".md") && line.match?(FIRST_PERSON)
      found << "#{file}:#{index + 1}: first person: #{line.strip}"
    end
    found
  end
end

if failures.empty?
  puts "prose ok"
  exit 0
end

warn failures.join("\n")
warn "\n#{failures.length} prose violation(s)"
exit 1
